// <auto-generated />
namespace EFTuts.Data.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialize_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialize_database));
        
        string IMigrationMetadata.Id
        {
            get { return "201804051228262_initialize_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
